# Generated by Django 2.2.18 on 2021-02-11 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devapp', '0002_auto_20210211_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiods',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='activityperiods',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
